repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    -   id: check-merge-conflict
        stages:
        - push
    -   id: double-quote-string-fixer
        stages:
        - commit
        - push
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args: [--config=flake8.cfg]
        stages:
        - commit
        - push
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.8
