version: '3'

volumes:
  postgres_data:

services:
  postgres:
    image: postgres:12.7-alpine
    ports:
      - 5432:5432
    environment:  # todo change to .env
      POSTGRES_DB: mf
      POSTGRES_USER: mf
      POSTGRES_PASSWORD: mf
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

#  flower:
#    image: mher/flower:0.9.7
#    env_file:
#      - .env
#    ports:
#      - 5555:5555