version: '3'

services:
  postgres:
    image: postgres:12.7-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: docker_myfoods
      POSTGRES_USER: karimmm
      POSTGRES_PASSWORD: sore.throat
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

volumes:
  db:
