version: '3'

volumes:
  postgres_data:
  grafana_volume:

services:
  postgres:
    image: postgres:12.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  flower:
    image: mher/flower:0.9.7
    env_file:
      - .env
    ports:
      - 5555:5555

  promtail:
    image: grafana/promtail:1.4.1
    volumes:
      - /var/log:/var/log
      - ./promtail/promtail.yaml:/etc/promtail/promtail.yml
    command:
      - '-config.file=/etc/promtail/promtail.yml'

#  grafana:
#    image: grafana/grafana:8.1.2
#    volumes:
#      - ./grafana/provisioning/:/etc/grafana/provisioning/
#      - grafana_volume:/var/lib/grafana/
#    env_file:
#      - .env
#    ports:
#      - 3000:3000
#    depends_on:
#      - postgres


