version: '3'

volumes:
  postgres_data:
  staticfiles_prod:

services:

  postgres:
    image: postgres:12.7-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - 5432
    logging:
      driver: loki
      options:
        loki-url: https://${GRAFANA_USER}:${GRAFANA_PASSWORD}@logs-prod3.grafana.net/loki/api/v1/push

  redis:
    image: redis:6-alpine
    expose:
      - 6379

  nginx:
    build:
      context: ./
      dockerfile: deploy/nginx/Dockerfile
    restart: always
    volumes:
      - staticfiles_prod:/staticfiles/
    ports:
      - 80:80
    logging:
      driver: loki
      options:
        loki-url: https://${GRAFANA_USER}:${GRAFANA_PASSWORD}@logs-prod3.grafana.net/loki/api/v1/push
    depends_on:
      - django

#""" todo start launching Docker as not root user
#""" todo add self-hosted github runner
#""" todo wrap everything with minikube

  django:
    build:
      context: ./
      dockerfile: deploy/python/django/Dockerfile
#      TODO: Add gunicorn
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - staticfiles_prod:/opt/app/src/staticfiles/
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - postgres
      - redis

  celery-beat:
    build:
      context: ./
      dockerfile: deploy/python/celery/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis
    command: celery -A myfoods beat -l info
    ports: []

  flower:
    image: mher/flower:0.9.7
    env_file:
      - ./.env
    ports:
      - 5555:5555
