# Generated by Django 3.1.7 on 2022-06-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_auto_20210608_1016"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(blank=True, default="default_profile_pic.jpg", upload_to=""),
        ),
    ]
