# Generated by Django 3.1.7 on 2022-06-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_auto_20220620_2349"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="like_counter",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
