# Generated by Django 3.1.7 on 2022-06-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20220621_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='icon',
            field=models.ImageField(blank=True, default='default-product-image.png', null=True, upload_to=''),
        ),
    ]
