name: Deploy

on:
  release:
    types: [ published ]
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy with docker-compose
        run: |
          cd ~/django-myfoods
          git checkout master
          git pull origin master
          sudo docker-compose -f docker-compose.prod.yml up --build -d
